variable "project" {}
variable "env" {}
variable "repo" {}
variable "cluster_arn" {}
variable "cluster_name" {}
variable "subnets_id" {}
variable "security_groups_id" {}
variable "execution_role_arn" {}
variable "vpc_id" {}
variable "region" {}
variable "cpu" {}
variable "memory" {}
variable "secrets" {}
variable "environment" {}
variable "command" {}
variable "ecr_name" {}
