# Generated by Django 4.1.2 on 2023-01-11 23:36

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_details',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='', max_length=100, size=6),
            preserve_default=False,
        ),
    ]
