# Generated by Django 4.1.2 on 2022-10-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehical_name',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehical_brand',
            new_name='vehicle_brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehical_overview',
            new_name='vehicle_overview',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_of_cost',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_of_sale',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehical_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_details',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_rent_active',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
