# Generated by Django 4.1.2 on 2023-04-23 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='accessories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default='', max_length=255, size=10),
            preserve_default=False,
        ),
    ]
