# Generated by Django 4.1.2 on 2023-02-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_vehicle_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
