# Generated by Django 4.1.2 on 2022-10-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_rename_vehical_name_vehicle_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
