# Generated by Django 4.1.2 on 2023-03-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_add_removed_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='vehical_image',
            new_name='vehicle_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_details',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Hybrid', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_year',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.IntegerField(default=None),
        ),
    ]
