# Generated by Django 4.1.2 on 2022-10-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_alter_vehicledocument_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_document',
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='vehicle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle'),
            preserve_default=False,
        ),
    ]
