# Generated by Django 4.1.2 on 2023-03-02 04:38

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_rename_vehical_image_vehicleimage_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='accessories',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), default=[], max_length=255, size=10),
            preserve_default=False,
        ),
    ]
