# Generated by Django 4.1.2 on 2022-11-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicleimage_vehicle_alter_vehicledocument_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_image', to='vehicle.vehicle'),
        ),
    ]
