# Generated by Django 4.1.2 on 2023-03-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicle_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
