# Generated by Django 4.1.2 on 2022-11-09 17:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_vehicleimage_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='accessory',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), default='', size=8),
            preserve_default=False,
        ),
    ]
