# Generated by Django 4.1.2 on 2023-01-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_vehicleimage_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_details',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicledetails'),
            preserve_default=False,
        ),
    ]
