# Generated by Django 4.1.2 on 2023-01-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_vehicle_vehicle_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_details',
        ),
    ]
