# Generated by Django 4.1.2 on 2023-01-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_remove_vehicle_vehicle_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price_of_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_of_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=999),
        ),
    ]
