# Generated by Django 4.1.2 on 2023-01-01 23:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_vehicle_price_of_cost_vehicle_price_of_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=['testing'], size=None),
            preserve_default=False,
        ),
    ]
