# Generated by Django 4.1.2 on 2023-01-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_vehicle_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='tags',
            new_name='vehicle_details',
        ),
    ]
